Bumped libbuildpack-dynatrace to 1.4.1
cloudfoundry/nodejs-buildpack pull request #347
Opened 2021-07-14 09:31 UTC by arthfl

* A short explanation of the proposed change:
Bumped  libbuildpack-dynatrace to 1.4.1 to include the networkzone parameter when downloading the OneAgent from the API
* An explanation of the use cases your change solves
This includes the networkzone parameter when downloading the OneAgent from the API
* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [x] I have added an integration test

2021-08-17 11:31 UTC, arthfl commented
Dear maintainers, any ETA on this?

2021-08-18 15:19 UTC, arjun024 commented
@arthfl Looking into this now

2021-08-18 15:39 UTC, arjun024 requested changes

2021-08-18 15:39 UTC, arjun024 commented on src/nodejs/integration/nodejs_app_with_dynatrace_test.go
> +			createdServices = append(createdServices, serviceName)
What is `createdServices` here?

2021-08-23 17:44 UTC, merged